kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-cluster
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30008 #Referência ao primeiro parâmetro do mapeamento de um container no comando docker run
    hostPort: 80 #Segundo parâmetro
    protocol: TCP
