apiVersion: v1
kind: Service
metadata:
  name: viacep-service
spec:
  type: NodePort
  selector:
    app: viacep-api
  ports:
    - name: viacep-nginx
      port: 80
      targetPort: 80
      nodePort: 30009